import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


class TestFrontendFiles(unittest.TestCase):
    def test_index_references_assets(self):
        content = (ROOT / "frontend" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="gameRows"', content)
        self.assertIn('id="searchInput"', content)
        self.assertIn('id="importForm"', content)
        self.assertIn('id="kifFileInput"', content)
        self.assertIn('id="directoryImportForm"', content)
        self.assertIn('id="directoryPathInput"', content)
        self.assertIn('id="recursiveImportInput"', content)
        self.assertIn('id="cancelDirectoryImportButton"', content)
        self.assertIn('id="openingRebuildSummary"', content)
        self.assertIn('id="openingRebuildButton"', content)
        self.assertIn('id="cancelOpeningRebuildButton"', content)
        self.assertIn('class="registration-controls"', content)
        self.assertIn('accept=".kif,text/plain,application/octet-stream"', content)
        self.assertIn('id="strategyStatsPanel"', content)
        self.assertIn('id="strategyStatsList"', content)
        self.assertIn('id="enclosureStatsPanel"', content)
        self.assertIn('id="enclosureStatsList"', content)
        self.assertIn('id="blunderPanel"', content)
        self.assertIn('id="blunderList"', content)
        self.assertIn('id="openingManagementPanel"', content)
        self.assertIn('id="openingManagementSummary"', content)
        self.assertIn('<span id="openingManagementSummary">定跡として登録する棋譜</span>', content)
        self.assertNotIn(">professional<", content)
        self.assertIn('id="openingImportForm"', content)
        self.assertIn('id="openingFileInput"', content)
        self.assertIn('id="openingFileName"', content)
        self.assertIn('id="openingImportButton"', content)
        self.assertIn('id="openingDirectoryImportForm"', content)
        self.assertIn('id="openingDirectoryPathInput"', content)
        self.assertIn('id="openingRecursiveImportInput"', content)
        self.assertIn('id="openingDirectoryImportButton"', content)
        self.assertIn('id="openingCancelDirectoryImportButton"', content)
        self.assertIn('aria-label="定跡登録"', content)
        self.assertIn('id="viewerView"', content)
        self.assertIn('id="boardGrid"', content)
        self.assertIn('id="evalGraph"', content)
        self.assertIn('id="moveFrequencyList"', content)
        self.assertIn('id="moveFrequencySummary"', content)
        self.assertIn('id="openingList"', content)
        self.assertIn('id="openingSummary"', content)
        self.assertIn('id="openingComparisonSummary"', content)
        self.assertIn('id="openingComparisonMissing"', content)
        self.assertIn('id="openingComparisonPrompt"', content)
        self.assertIn('id="openingComparisonOutput"', content)
        self.assertIn('id="buildOpeningComparisonButton"', content)
        self.assertIn('id="generateOpeningComparisonButton"', content)
        self.assertIn('id="explanationSummary"', content)
        self.assertIn('id="explanationMissing"', content)
        self.assertIn('id="explanationPrompt"', content)
        self.assertIn('id="explanationOutput"', content)
        self.assertIn('id="buildExplanationPromptButton"', content)
        self.assertIn('id="generateExplanationButton"', content)
        self.assertIn('id="moveSlider"', content)
        self.assertIn('id="positionEval"', content)
        self.assertIn('id="candidateSummary"', content)
        self.assertIn('id="candidateList"', content)
        self.assertIn('id="candidateStatus"', content)
        self.assertIn('id="analyzeCandidateButton"', content)
        self.assertIn('id="blackHand"', content)
        self.assertIn('id="whiteHand"', content)
        self.assertIn('/assets/styles.css', content)
        self.assertIn('/assets/app.js', content)

    def test_app_fetches_games_endpoint(self):
        content = (ROOT / "frontend" / "assets" / "app.js").read_text(encoding="utf-8")

        self.assertIn('fetch("/api/games")', content)
        self.assertIn('fetch("/api/stats/strategies")', content)
        self.assertIn('fetch("/api/stats/enclosures")', content)
        self.assertIn('fetch("/api/stats/blunders")', content)
        self.assertIn('fetch("/api/games/import"', content)
        self.assertIn('fetch("/api/games/import-directory"', content)
        self.assertIn('"Content-Type": "application/octet-stream"', content)
        self.assertIn("importKifFile", content)
        self.assertIn("importKifDirectory", content)
        self.assertIn("pollDirectoryImportJob", content)
        self.assertIn("setDirectoryImportStatus", content)
        self.assertIn("cancelDirectoryImport", content)
        self.assertIn("processed}/${total}", content)
        self.assertIn("kifFileInput.addEventListener", content)
        self.assertIn("directoryImportForm.addEventListener", content)
        self.assertIn("cancelDirectoryImportButton.addEventListener", content)
        self.assertIn('fetch("/api/openings/rebuild"', content)
        self.assertIn('fetch(`/api/openings/rebuild/jobs/${jobId}`)', content)
        self.assertIn('fetch(`/api/openings/rebuild/jobs/${jobId}/cancel`', content)
        self.assertIn("rebuildOpenings", content)
        self.assertIn("pollOpeningRebuildJob", content)
        self.assertIn("cancelOpeningRebuild", content)
        self.assertIn("openingRebuildButton.addEventListener", content)
        self.assertIn("renderStrategyStats", content)
        self.assertIn("renderEnclosureStats", content)
        self.assertIn("renderBlunders", content)
        self.assertIn("blunder.occurrence_count", content)
        self.assertIn("blunder.game_count", content)
        self.assertIn("moveLabelForCandidate(blunder.move, blunder.previous_sfen)", content)
        self.assertIn("generateBlunderExplanation", content)
        self.assertIn('fetch("/api/blunders/explain"', content)
        self.assertIn("blunderKey", content)
        self.assertIn("openBlunderPosition", content)
        self.assertIn('`/games/${blunder.game_id}?move=${blunder.move_number}`', content)
        self.assertIn("loadStats", content)
        self.assertIn("renderStatsList", content)
        self.assertIn("formatPercent", content)
        self.assertIn("parseSfen", content)
        self.assertIn("renderBoard", content)
        self.assertIn("currentMoveInfo", content)
        self.assertIn("moveInfoForPosition", content)
        self.assertIn("moveLabelForCandidate", content)
        self.assertIn("moveLabelForCandidate(frequency.move", content)
        self.assertIn("moveLabelForCandidate(opening.move", content)
        self.assertIn("parseUsiMove", content)
        self.assertIn("isMoveSquare", content)
        self.assertIn("renderEngineCandidates", content)
        self.assertIn("selectedCandidateMoveInfo", content)
        self.assertIn("selectedCandidateMove", content)
        self.assertIn("candidateAnalysisStatus", content)
        self.assertIn("candidateStatusText", content)
        self.assertIn("analyzeCurrentPositionForCandidates", content)
        self.assertIn('fetch(`/api/positions/${position.id}/analyze`', content)
        self.assertIn("payload.error || `HTTP ${response.status}`", content)
        self.assertIn("analyzeCandidateButton.addEventListener", content)
        self.assertIn("この局面を解析してください", content)
        self.assertIn("candidate.move === actualMove", content)
        self.assertIn("sameDestination", content)
        self.assertIn('sameDestination ? "同"', content)
        self.assertIn("renderEvalGraph", content)
        self.assertIn("formatEvalWithDelta", content)
        self.assertIn("mateEvalValue = 100000", content)
        self.assertIn("evalGraphMinScale = 3000", content)
        self.assertIn("evalGraphMaxScale = 3000", content)
        self.assertIn("isMateEval", content)
        self.assertIn("isClippedEval", content)
        self.assertIn("buildEvalScale", content)
        self.assertIn("表示上限外", content)
        self.assertIn("drawMissingEvalLines", content)
        self.assertIn('"+詰み"', content)
        self.assertIn('circle.addEventListener("click", () => setCurrentMove(point.index))', content)
        self.assertIn("moveNumberFromQuery", content)
        self.assertIn('new URLSearchParams(window.location.search).get("move")', content)
        self.assertIn('moveSlider.addEventListener("input"', content)
        self.assertIn('fetch(`/api/games/${gameId}/positions`)', content)
        self.assertIn('fetch(`/api/positions?sfen=${encodeURIComponent(position.sfen)}`)', content)
        self.assertIn("fetch(`/api/openings?${query.toString()}`)", content)
        self.assertIn('source: "professional"', content)
        self.assertIn('fetch("/api/openings/import?source=professional"', content)
        self.assertIn('fetch("/api/openings/import-directory"', content)
        self.assertIn('fetch(`/api/openings/import-directory/jobs/${jobId}`)', content)
        self.assertIn('fetch(`/api/openings/import-directory/jobs/${jobId}/cancel`', content)
        self.assertIn("importOpeningDirectory", content)
        self.assertIn("pollOpeningDirectoryImportJob", content)
        self.assertIn("setOpeningDirectoryImportStatus", content)
        self.assertIn("cancelOpeningDirectoryImport", content)
        self.assertIn("openingCancelDirectoryImportButton.addEventListener", content)
        self.assertIn("定跡一括登録中", content)
        self.assertIn("renderMoveFrequencies", content)
        self.assertIn("loadMoveFrequencies", content)
        self.assertIn("renderOpenings", content)
        self.assertIn("loadOpenings", content)
        self.assertIn("importOpeningFile", content)
        self.assertIn("openingManagementSummary", content)
        self.assertIn("openingImportForm.addEventListener", content)
        self.assertIn("renderOpeningComparison", content)
        self.assertIn("resetOpeningComparison", content)
        self.assertIn("loadOpeningComparisonPrompt", content)
        self.assertIn("generateOpeningComparison", content)
        self.assertIn('fetch(`/api/positions/${position.id}/opening-comparison-prompt?', content)
        self.assertIn('fetch(`/api/positions/${position.id}/opening-comparison-explain`', content)
        self.assertIn("buildOpeningComparisonButton.addEventListener", content)
        self.assertIn("generateOpeningComparisonButton.addEventListener", content)
        self.assertIn("renderExplanationPrompt", content)
        self.assertIn("resetExplanationPrompt", content)
        self.assertIn("loadExplanationPrompt", content)
        self.assertIn("generateExplanation", content)
        self.assertIn('fetch(`/api/positions/${position.id}/explanation-prompt`)', content)
        self.assertIn('fetch(`/api/positions/${position.id}/explain`', content)
        self.assertIn("JSON.stringify({})", content)
        self.assertIn("buildExplanationPromptButton.addEventListener", content)
        self.assertIn("generateExplanationButton.addEventListener", content)
        self.assertIn('window.location.href = `/games/${game.id}`', content)
        self.assertIn("保存済み対局はありません", content)

    def test_styles_define_table_layout(self):
        content = (ROOT / "frontend" / "assets" / "styles.css").read_text(encoding="utf-8")

        self.assertIn(".game-table", content)
        self.assertIn(".import-form", content)
        self.assertIn(".directory-import-form", content)
        self.assertIn(".registration-controls", content)
        self.assertIn("[hidden]", content)
        self.assertIn(".checkbox-field", content)
        self.assertIn(".file-picker", content)
        self.assertIn(".stats-panel", content)
        self.assertIn(".management-panel", content)
        self.assertIn(".stats-item", content)
        self.assertIn(".stats-list", content)
        self.assertIn(".stats-item-actions", content)
        self.assertIn(".blunder-explanation-output", content)
        self.assertIn("overflow-y: auto", content)
        self.assertIn("max-height: 242px", content)
        self.assertIn("table-layout: fixed", content)
        self.assertIn(".board-grid", content)
        self.assertIn(".square.move-from", content)
        self.assertIn(".square.move-to", content)
        self.assertIn(".eval-graph", content)
        self.assertIn(".move-frequency-panel", content)
        self.assertIn(".move-frequency-list", content)
        self.assertIn("max-height: 206px", content)
        self.assertIn(".move-frequency-bar", content)
        self.assertIn(".candidate-panel", content)
        self.assertIn(".candidate-item", content)
        self.assertIn(".candidate-item.selected", content)
        self.assertIn(".candidate-item.actual", content)
        self.assertIn(".opening-panel", content)
        self.assertIn(".opening-bar", content)
        self.assertIn(".opening-comparison-prompt", content)
        self.assertIn(".opening-comparison-output", content)
        self.assertIn(".opening-comparison-missing", content)
        self.assertIn(".explanation-panel", content)
        self.assertIn(".explanation-prompt", content)
        self.assertIn(".explanation-output", content)
        self.assertIn(".explanation-missing", content)
        self.assertIn(".panel-heading-actions", content)
        self.assertIn(".eval-line", content)
        self.assertIn(".eval-missing-line", content)
        self.assertIn(".eval-point.current", content)
        self.assertIn(".eval-point:hover", content)
        self.assertIn(".move-slider", content)
        self.assertIn("aspect-ratio: 1", content)
        self.assertIn("@media (max-width: 640px)", content)


if __name__ == "__main__":
    unittest.main(verbosity=2)
